# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I make things!
email: keithcharlieom@gmail.com
description: >
  Hey there, my name is Keith and I love making things, like music, 3D models, websites, Unity games and messing around with computers
baseurl: ""
url: "http://keithomalley.com"
twitter_username: keithomaille
github_username:  keithomalley
dribbble_username:  keithomalley

# Build settings
markdown: kramdown
